site_name: The Nomad Chronicles (TNC)
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Player’s Manual:
      - Introduction: intro.md
      - Core Rules: core-rules.md
      - Character Creation: character-creation.md
      - Equipment: equipment.md
  - Bestiary: bestiary.md
  - Appendix: appendix.md
  - Tools:
    - Digital Character Sheet: sheet/index.html